name: 'AWS Lambda FunctionCode Update'
description: 'Run UpdateFunctionCode , PublishVersion'
author: 'taotao2345'
inputs: 
  function_name:
    description: 'Target function name'
    required: true
  zip_file:
    description: 'Package zip file path'
    required: true
  publish:
    description: '`true` to run PublishVersion operation. Default: `false`'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'